AWSTemplateFormatVersion: '2010-09-09'
Description: Create an S3 bucket named project-ambifi-bucket, a project IAM managed policy, and an IAM role for accessing that bucket

Resources:

  ProjectAmbifiBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: project-ambifi-bucket

  rS3Policy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Project Administrator created S3 Policy
      Path: /project/
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: S3ListAllBuckets
            Effect: Allow
            Action:
              - s3:ListAllMyBuckets
            Resource: '*'

          - Sid: AllowS3LimitedAccess
            Effect: Allow
            Action:
              - s3:ListBucket
              - s3:GetObject
              - s3:GetObjectVersion
            Resource:
              - !Sub arn:${AWS::Partition}:s3:::project-ambifi-bucket
              - !Sub arn:${AWS::Partition}:s3:::project-ambifi-bucket/*

  ProjectAmbifiS3AccessRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /project/
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - !Ref rS3Policy
